config/routes.rb
Rails.application.routes.draw do
  resources :robots
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'robots#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/robot.rb
class Robot < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  before_action :set_robot, only: [:show, :edit, :update, :destroy]
  # GET /robots
  # GET /robots.json
  def index
    @robots = Robot.all
  end

  # GET /robots/1
  # GET /robots/1.json
  def show
  end

  # GET /robots/new
  def new
    @robot = Robot.new
  end

  # GET /robots/1/edit
  def edit
  end

  # POST /robots
  # POST /robots.json
  def create
    @robot = Robot.new(robot_params)

    respond_to do |format|
      if @robot.save
        format.html { redirect_to @robot, notice: 'Robot was successfully created.' }
        format.json { render :show, status: :created, location: @robot }
      else
        format.html { render :new }
        format.json { render json: @robot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /robots/1
  # PATCH/PUT /robots/1.json
  def update
    respond_to do |format|
      if @robot.update(robot_params)
        format.html { redirect_to robots_url, notice: 'Robot was successfully updated.' }
        format.json { render :show, status: :ok, location: @robot }
      else
        format.html { render :edit }
        format.json { render json: @robot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /robots/1
  # DELETE /robots/1.json
  def destroy
    @robot.destroy
    respond_to do |format|
      format.html { redirect_to robots_url, notice: 'Robot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_robot
      @robot = Robot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def robot_params
      params.require(:robot).permit(:model, :serial_number, :external_sockets, :has_wheels, :date_of_manufacture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/robots_helper.rb
module RobotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProblemChild</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/robots/_form.html.erb
<%= form_for(@robot) do |f| %>
  <% if @robot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(robot.errors.count, "error") %> prohibited this robot from being saved:</h2>

      <ul>
      <% robot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>

  <div class="field">
    <%= f.label :serial_number %>
    <%= f.text_field :serial_number %>
  </div>

  <div class="field">
    <%= f.label :external_sockets %>
    <%= f.text_field :external_sockets %>
  </div>

  <div class="field">
    <%= f.label :has_wheels %>
    <%= f.check_box :has_wheels %>
  </div>

  <div class="field">
    <%= f.label :date_of_manufacture %>
    <%= f.date_select :date_of_manufacture %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/robots/edit.html.erb
<h1>Editing Robot</h1>

<%= render 'form', robot: @robot %>

<%= link_to 'Show', @robot %> |
<%= link_to 'Back', robots_path %>

app/views/robots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Robots</h1>

<table>
  <thead>
    <tr>
      <th>Picture</th>
      <th>Model</th>
      <th>Serial number</th>
      <th>External sockets</th>
      <th>Has wheels</th>
      <th>Date of manufacture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @robots.each do |robot| %>
      <tr>
        <td><img src='https://robohash.org/<%= robot.model %>?size=50x50'></td>
        <td><%= robot.model %></td>
        <td><%= robot.serial_number %></td>
        <td><%= robot.external_sockets %></td>
        <td><%= robot.has_wheels %></td>
        <td><%= robot.date_of_manufacture %></td>
        <td><%= link_to 'Show', robot %></td>
        <td><%= link_to 'Edit', edit_robot_path(robot) %></td>
        <td><%= link_to 'Destroy', robot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Robot', new_robot_url %>

app/views/robots/new.html.erb
<h1>New Robot</h1>

<%= render 'form', robot: @robot %>

<%= link_to 'Back', robots_path %>

app/views/robots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @robot.model %>
</p>

<p>
  <strong>Serial number:</strong>
  <%= @robot.serial_number %>
</p>

<p>
  <strong>External sockets:</strong>
  <%= @robot.external_sockets %>
</p>

<p>
  <strong>Has wheels:</strong>
  <%= @robot.has_wheels %>
</p>

<p>
  <strong>Date of manufacture:</strong>
  <%= @robot.date_of_manufacture %>
</p>

<%= link_to 'Edit', edit_robot_path(@robot) %> |
<%= link_to 'Back', robots_path %>